#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3 effective-4.1.50 (swiftlang-6.3.0.123.5 clang-2100.0.123.102)
#ifndef BCDRAMALIB_SWIFT_H
#define BCDRAMALIB_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="BCDramaLib",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import TXLiteAVSDK_Professional;
@import UIKit;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="BCDramaLib",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

SWIFT_ENUM_FWD_DECL(NSInteger, BCAdPlatformType)
@class NSString;
SWIFT_ENUM_FWD_DECL(NSInteger, BCAdType)
SWIFT_PROTOCOL("_TtP10BCDramaLib11BCAdAdapter_")
@protocol BCAdAdapter <NSObject>
@property (nonatomic, readonly) enum BCAdPlatformType platformType;
- (void)registerSDKWithAppId:(NSString * _Nonnull)appId;
@optional
- (void)fetchECPMWithPlacementId:(NSString * _Nonnull)placementId adType:(enum BCAdType)adType completion:(void (^ _Nonnull)(NSInteger))completion;
@end

SWIFT_CLASS("_TtC10BCDramaLib19BCAdAdapterRegistry")
@interface BCAdAdapterRegistry : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) BCAdAdapterRegistry * _Nonnull shared;)
+ (BCAdAdapterRegistry * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (void)register:(NSArray<id <BCAdAdapter>> * _Nonnull)adapters;
- (id <BCAdAdapter> _Nullable)adapterFor:(enum BCAdPlatformType)platform SWIFT_WARN_UNUSED_RESULT;
- (id <BCAdAdapter> _Nullable)adapterForAdPlatform:(NSInteger)adPlatform SWIFT_WARN_UNUSED_RESULT;
- (void)pauseMSaasPlaybackIfRegistered;
- (void)registerSDKIfNeededWithAppId:(NSString * _Nonnull)appId adPlatform:(NSInteger)adPlatform;
@end

/// 激励视频页关闭后通知（Core 与 Adapter 共用）
SWIFT_CLASS("_TtC10BCDramaLib17BCAdNotifications")
@interface BCAdNotifications : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull fromRewardVCName;)
+ (NSString * _Nonnull)fromRewardVCName SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, BCAdPlatformType, open) {
  BCAdPlatformTypeGdt = 1,
  BCAdPlatformTypeCsj = 3,
  BCAdPlatformTypeMsaas = 4,
  BCAdPlatformTypeKs = 5,
  BCAdPlatformTypeCustom = 6,
};

typedef SWIFT_ENUM(NSInteger, BCAdStatues, open) {
  BCAdStatuesSuccess = 0,
  BCAdStatuesClose = 1,
  BCAdStatuesFailed = 2,
};

typedef SWIFT_ENUM(NSInteger, BCAdType, open) {
  BCAdTypeBanner = 0,
  BCAdTypeReward = 1,
  BCAdTypeNativeExpress = 2,
  BCAdTypeFullScreen = 3,
};

@class NSCoder;
SWIFT_CLASS("_TtC10BCDramaLib12BCBaseBanner")
@interface BCBaseBanner : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (void)layoutSubviews;
- (void)removeFromSuperview;
@end

SWIFT_CLASS("_TtC10BCDramaLib8BCBanner")
@interface BCBanner : BCBaseBanner
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end

@class UICollectionView;
@class NSIndexPath;
@class UICollectionViewCell;
@interface BCBanner (SWIFT_EXTENSION(BCDramaLib)) <UICollectionViewDataSource, UICollectionViewDelegate>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end

@class UIScrollView;
@interface BCBanner (SWIFT_EXTENSION(BCDramaLib))
/// Began to drag and drop
- (void)scrollViewWillBeginDragging:(UIScrollView * _Nonnull)scrollView;
/// The drag is about to end
- (void)scrollViewWillEndDragging:(UIScrollView * _Nonnull)scrollView withVelocity:(CGPoint)velocity targetContentOffset:(CGPoint * _Nonnull)targetContentOffset;
/// It’s going to start slowing down
- (void)scrollViewWillBeginDecelerating:(UIScrollView * _Nonnull)scrollView;
/// End to slow down
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
/// Scroll animation complete
- (void)scrollViewDidEndScrollingAnimation:(UIScrollView * _Nonnull)scrollView;
/// Rolling in the
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
@end

@class UIViewController;
SWIFT_ENUM_FWD_DECL(NSInteger, BCCustomAdPageType)
SWIFT_PROTOCOL("_TtP10BCDramaLib17BCBannerAdAdapter_")
@protocol BCBannerAdAdapter <NSObject>
- (void)loadBannerWithViewController:(UIViewController * _Nonnull)viewController container:(UIView * _Nonnull)container placementId:(NSString * _Nonnull)placementId pageType:(enum BCCustomAdPageType)pageType onClose:(void (^ _Nonnull)(void))onClose onShow:(void (^ _Nonnull)(NSInteger))onShow;
- (void)removeBannerFrom:(UIView * _Nonnull)container;
@end

SWIFT_CLASS("_TtC10BCDramaLib16BCBannerBaseCell")
@interface BCBannerBaseCell : UICollectionViewCell
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC10BCDramaLib12BCBannerCell")
@interface BCBannerCell : BCBannerBaseCell
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@interface BCBaseBanner (SWIFT_EXTENSION(BCDramaLib))
- (void)willMoveToSuperview:(UIView * _Nullable)newSuperview;
@end

@class NSBundle;
SWIFT_CLASS("_TtC10BCDramaLib20BCBaseViewController")
@interface BCBaseViewController : UIViewController
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
@property (nonatomic, readonly) BOOL shouldAutorotate;
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
@property (nonatomic, readonly) UIInterfaceOrientation preferredInterfaceOrientationForPresentation;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC10BCDramaLib14BCCrashManager")
@interface BCCrashManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) BCCrashManager * _Nonnull shared;)
+ (BCCrashManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (void)startMonitoring;
- (NSArray<NSString *> * _Nonnull)getAllCrashLogs SWIFT_WARN_UNUSED_RESULT;
- (void)clearAllCrashLogs;
- (NSInteger)getCrashLogCount SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getLatestCrashLog SWIFT_WARN_UNUSED_RESULT;
@end

/// 显示插屏广告的位置页
typedef SWIFT_ENUM(NSInteger, BCCustomAdPageType, open) {
  BCCustomAdPageTypeRecommendPage = 0,
  BCCustomAdPageTypeNewRecommendPage = 1,
  BCCustomAdPageTypePlayPage = 2,
  BCCustomAdPageTypeFavorite = 3,
  BCCustomAdPageTypeDramas = 4,
};

SWIFT_CLASS_NAMED("BCDramaFavoriteListModel")
@interface BCDramaFavoriteListModel : NSObject
@property (nonatomic) NSInteger video_id;
@property (nonatomic) NSInteger video_total;
@property (nonatomic, copy) NSString * _Nonnull video_title;
@property (nonatomic, copy) NSString * _Nonnull logo_img;
@property (nonatomic) NSInteger episode_no;
@property (nonatomic, copy) NSString * _Nonnull last_play_time;
@property (nonatomic, copy) NSString * _Nonnull corner_label_name;
@property (nonatomic) NSInteger is_new_video;
@property (nonatomic) NSInteger last_episode_no;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// 剧单列表类型
typedef SWIFT_ENUM(NSInteger, BCDramaListType, open) {
  BCDramaListTypeCollection = 0,
  BCDramaListTypeHistory = 1,
};

/// 设置开发环境
typedef SWIFT_ENUM(NSInteger, BCEnvType, open) {
/// 测试环境
  BCEnvTypeDebug = 0,
/// 生产环境
  BCEnvTypeRelease = 1,
};

SWIFT_PROTOCOL("_TtP10BCDramaLib21BCFullScreenAdAdapter_")
@protocol BCFullScreenAdAdapter <NSObject>
- (void)showFullScreenWithViewController:(UIViewController * _Nonnull)viewController placementId:(NSString * _Nonnull)placementId pageType:(enum BCCustomAdPageType)pageType onShow:(void (^ _Nonnull)(void))onShow onClose:(void (^ _Nonnull)(void))onClose onFailed:(void (^ _Nonnull)(void))onFailed;
@end

SWIFT_CLASS_NAMED("BCGoodItemsModel")
@interface BCGoodItemsModel : NSObject
@property (nonatomic) NSInteger goodsId;
@property (nonatomic) NSInteger goodsType;
@property (nonatomic, copy) NSString * _Nonnull goodsTitle;
@property (nonatomic) double goodsPrice;
@property (nonatomic) double goodsPriceYuan;
@property (nonatomic, copy) NSString * _Nonnull describeText;
@property (nonatomic) NSInteger vipValidDays;
@property (nonatomic) NSInteger unlockEpisodeNum;
@property (nonatomic, copy) NSString * _Nonnull specialText;
@property (nonatomic) NSInteger isDefault;
@property (nonatomic) NSInteger payStrategyId;
@property (nonatomic) NSInteger goodsCoin;
@property (nonatomic, copy) NSString * _Nonnull goodsCoinName;
@property (nonatomic) NSInteger videoId;
@property (nonatomic) NSInteger episodeNo;
@property (nonatomic) NSInteger payMethod;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("BCGoodListModel")
@interface BCGoodListModel : NSObject
@property (nonatomic) NSInteger videoId;
@property (nonatomic) NSInteger episodeNo;
@property (nonatomic) NSInteger goodsId;
@property (nonatomic) NSInteger goodsType;
@property (nonatomic, copy) NSString * _Nonnull goodsTitle;
@property (nonatomic) double goodsPrice;
@property (nonatomic) double goodsPriceYuan;
@property (nonatomic, copy) NSString * _Nonnull describeText;
@property (nonatomic) NSInteger vipValidDays;
@property (nonatomic) NSInteger unlockEpisodeNum;
@property (nonatomic, copy) NSString * _Nonnull specialText;
@property (nonatomic) NSInteger isDefault;
@property (nonatomic) NSInteger payStrategyId;
@property (nonatomic) NSInteger goodsCoin;
@property (nonatomic, copy) NSString * _Nonnull goodsCoinName;
@property (nonatomic) NSInteger payMethod;
@property (nonatomic, copy) NSString * _Nonnull appleGoodsId;
@property (nonatomic, copy) NSString * _Nonnull googleGoodsId;
@property (nonatomic) NSInteger currencyId;
@property (nonatomic, copy) NSString * _Nonnull currencyName;
@property (nonatomic, copy) NSString * _Nonnull currencyCode;
@property (nonatomic, copy) NSString * _Nonnull currencySymbol;
- (nonnull instancetype)initWithGoodsId:(NSInteger)goodsId goodsType:(NSInteger)goodsType goodsTitle:(NSString * _Nonnull)goodsTitle goodsPrice:(double)goodsPrice goodsPriceYuan:(double)goodsPriceYuan describeText:(NSString * _Nonnull)describeText vipValidDays:(NSInteger)vipValidDays unlockEpisodeNum:(NSInteger)unlockEpisodeNum specialText:(NSString * _Nonnull)specialText isDefault:(NSInteger)isDefault payStrategyId:(NSInteger)payStrategyId goodsCoin:(NSInteger)goodsCoin goodsCoinName:(NSString * _Nonnull)goodsCoinName payMethod:(NSInteger)payMethod videoId:(NSInteger)videoId episodeNo:(NSInteger)episodeNo appleGoodsId:(NSString * _Nonnull)appleGoodsId googleGoodsId:(NSString * _Nonnull)googleGoodsId currencyId:(NSInteger)currencyId currencyName:(NSString * _Nonnull)currencyName currencyCode:(NSString * _Nonnull)currencyCode currencySymbol:(NSString * _Nonnull)currencySymbol OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

/// 商品列表
typedef SWIFT_ENUM(NSInteger, BCGoodListType, open) {
  BCGoodListTypeDefaults = 0,
  BCGoodListTypeHalf = 1,
  BCGoodListTypeCustom = 2,
};

typedef SWIFT_ENUM(NSInteger, BCLanguageType, open) {
  BCLanguageTypeCn = 1,
  BCLanguageTypeEn = 2,
  BCLanguageTypeJa = 4,
  BCLanguageTypeEs = 5,
  BCLanguageTypeKo = 7,
  BCLanguageTypeVi = 8,
  BCLanguageTypeCt = 9,
};

typedef SWIFT_ENUM(NSInteger, BCLaunchType, open) {
  BCLaunchTypeIap = 1,
  BCLaunchTypeIaa = 2,
};

SWIFT_CLASS("_TtC10BCDramaLib20BCLocalizableManager")
@interface BCLocalizableManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) BCLocalizableManager * _Nonnull shared;)
+ (BCLocalizableManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC10BCDramaLib14BCLoginManager")
@interface BCLoginManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) BCLoginManager * _Nonnull shared;)
+ (BCLoginManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) NSString * _Nonnull userId;
@property (nonatomic) BOOL isMute;
@property (nonatomic) BOOL isOpenCustomAd;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

/// 芒果 MSaas 播放暂停（由 BCDramaAdMSaas 实现）
SWIFT_PROTOCOL("_TtP10BCDramaLib22BCMSaasPlaybackAdapter_")
@protocol BCMSaasPlaybackAdapter <NSObject>
- (void)pauseMSaasPlayback;
@end

@class BCNativeExpressAdCollectionViewCell;
SWIFT_PROTOCOL("_TtP10BCDramaLib24BCNativeExpressAdAdapter_")
@protocol BCNativeExpressAdAdapter <NSObject>
- (void)prepareNativeExpressWithViewController:(UIViewController * _Nonnull)viewController placementId:(NSString * _Nonnull)placementId pageType:(enum BCCustomAdPageType)pageType adSize:(CGSize)adSize;
- (void)loadNativeExpressWithViewController:(UIViewController * _Nonnull)viewController container:(BCNativeExpressAdCollectionViewCell * _Nonnull)container pageType:(enum BCCustomAdPageType)pageType placementId:(NSString * _Nonnull)placementId completion:(void (^ _Nonnull)(UIView * _Nonnull, NSString * _Nonnull, NSError * _Nullable))completion;
@optional
- (void)setNativeAdMute:(BOOL)isMute;
@end

@class UIImageView;
SWIFT_CLASS("_TtC10BCDramaLib35BCNativeExpressAdCollectionViewCell")
@interface BCNativeExpressAdCollectionViewCell : UICollectionViewCell
@property (nonatomic, strong) UIImageView * _Null_unspecified vendorAdImageView;
@property (nonatomic, weak) BCNativeExpressAdCollectionViewCell * _Nullable vendorMsaasCellRef;
@property (nonatomic) id _Nullable vendorMsaasAdData;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (void)layoutSubviews;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS_NAMED("BCOrderListModel")
@interface BCOrderListModel : NSObject
@property (nonatomic, copy) NSString * _Nonnull order_no;
@property (nonatomic, copy) NSString * _Nonnull goods_name;
@property (nonatomic) CGFloat paid_fee;
@property (nonatomic) NSInteger pay_state;
@property (nonatomic, copy) NSString * _Nonnull pay_time;
@property (nonatomic) CGFloat refund_fee;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC10BCDramaLib25BCPagingListContainerView")
@interface BCPagingListContainerView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)willMoveToSuperview:(UIView * _Nullable)newSuperview;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class UICollectionViewLayout;
@interface BCPagingListContainerView (SWIFT_EXTENSION(BCDramaLib)) <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewWillBeginDragging:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDragging:(UIScrollView * _Nonnull)scrollView willDecelerate:(BOOL)decelerate;
- (void)scrollViewDidEndScrollingAnimation:(UIScrollView * _Nonnull)scrollView;
@end

SWIFT_CLASS("_TtC10BCDramaLib12BCPagingView")
@interface BCPagingView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS("_TtC10BCDramaLib23BCPagingListRefreshView")
@interface BCPagingListRefreshView : BCPagingView
@end

@class UIGestureRecognizer;
SWIFT_CLASS("_TtC10BCDramaLib21BCPagingMainTableView")
@interface BCPagingMainTableView : UITableView <UIGestureRecognizerDelegate>
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer * _Nonnull)otherGestureRecognizer SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame style:(UITableViewStyle)style OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_PROTOCOL("_TtP10BCDramaLib36BCPagingMainTableViewGestureDelegate_")
@protocol BCPagingMainTableViewGestureDelegate
- (BOOL)mainTableViewGestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldRecognizeSimultaneouslyWith:(UIGestureRecognizer * _Nonnull)otherGestureRecognizer SWIFT_WARN_UNUSED_RESULT;
@end

@class UITouch;
SWIFT_CLASS("_TtC10BCDramaLib28BCPagingSmoothCollectionView")
@interface BCPagingSmoothCollectionView : UICollectionView <UIGestureRecognizerDelegate>
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldReceiveTouch:(UITouch * _Nonnull)touch SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame collectionViewLayout:(UICollectionViewLayout * _Nonnull)layout OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC10BCDramaLib18BCPagingSmoothView")
@interface BCPagingSmoothView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (void)observeValueForKeyPath:(NSString * _Nullable)keyPath ofObject:(id _Nullable)object change:(NSDictionary<NSKeyValueChangeKey, id> * _Nullable)change context:(void * _Nullable)context;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@interface BCPagingSmoothView (SWIFT_EXTENSION(BCDramaLib)) <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView willDisplayCell:(UICollectionViewCell * _Nonnull)cell forItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didEndDisplayingCell:(UICollectionViewCell * _Nonnull)cell forItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDragging:(UIScrollView * _Nonnull)scrollView willDecelerate:(BOOL)decelerate;
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
@end

@protocol BCPagingSmoothViewListViewDelegate;
SWIFT_PROTOCOL("_TtP10BCDramaLib28BCPagingSmoothViewDataSource_")
@protocol BCPagingSmoothViewDataSource
/// 返回页面header的高度
- (CGFloat)heightForPagingHeaderIn:(BCPagingSmoothView * _Nonnull)pagingView SWIFT_WARN_UNUSED_RESULT;
/// 返回页面header视图
- (UIView * _Nonnull)viewForPagingHeaderIn:(BCPagingSmoothView * _Nonnull)pagingView SWIFT_WARN_UNUSED_RESULT;
/// 返回悬浮视图的高度
- (CGFloat)heightForPinHeaderIn:(BCPagingSmoothView * _Nonnull)pagingView SWIFT_WARN_UNUSED_RESULT;
/// 返回悬浮视图
- (UIView * _Nonnull)viewForPinHeaderIn:(BCPagingSmoothView * _Nonnull)pagingView SWIFT_WARN_UNUSED_RESULT;
/// 返回列表的数量
- (NSInteger)numberOfListsIn:(BCPagingSmoothView * _Nonnull)pagingView SWIFT_WARN_UNUSED_RESULT;
/// 根据index初始化一个对应列表实例，需要是遵从<code>BCPagingSmoothViewListViewDelegate</code>协议的对象。
/// 如果列表是用自定义UIView封装的，就让自定义UIView遵从<code>BCPagingSmoothViewListViewDelegate</code>协议，该方法返回自定义UIView即可。
/// 如果列表是用自定义UIViewController封装的，就让自定义UIViewController遵从<code>BCPagingSmoothViewListViewDelegate</code>协议，该方法返回自定义UIViewController即可。
- (id <BCPagingSmoothViewListViewDelegate> _Nonnull)pagingView:(BCPagingSmoothView * _Nonnull)pagingView initListAtIndex:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_PROTOCOL("_TtP10BCDramaLib26BCPagingSmoothViewDelegate_")
@protocol BCPagingSmoothViewDelegate
@optional
- (void)pagingSmoothViewDidScroll:(UIScrollView * _Nonnull)scrollView;
@end

SWIFT_PROTOCOL("_TtP10BCDramaLib34BCPagingSmoothViewListViewDelegate_")
@protocol BCPagingSmoothViewListViewDelegate
/// 返回listView。如果是vc包裹的就是vc.view；如果是自定义view包裹的，就是自定义view自己。
- (UIView * _Nonnull)listView SWIFT_WARN_UNUSED_RESULT;
/// 返回列表内部持有的 UIScrollView、UITableView 或 UICollectionView
- (UIScrollView * _Nonnull)listScrollView SWIFT_WARN_UNUSED_RESULT;
@optional
- (void)listDidAppear;
- (void)listDidDisappear;
@end

@class UITableViewCell;
@interface BCPagingView (SWIFT_EXTENSION(BCDramaLib)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewWillBeginDragging:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDragging:(UIScrollView * _Nonnull)scrollView willDecelerate:(BOOL)decelerate;
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndScrollingAnimation:(UIScrollView * _Nonnull)scrollView;
@end

SWIFT_CLASS_NAMED("BCPayOrderModel")
@interface BCPayOrderModel : NSObject
@property (nonatomic) NSInteger page;
@property (nonatomic) NSInteger page_size;
@property (nonatomic) NSInteger total;
@property (nonatomic) NSInteger pages;
@property (nonatomic, copy) NSArray<BCOrderListModel *> * _Nonnull list;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// 关闭SDK支付功能：0：关闭 1：开启
typedef SWIFT_ENUM(NSInteger, BCPaymentStatus, open) {
  BCPaymentStatusOff = 0,
  BCPaymentStatusOn = 1,
};

typedef SWIFT_ENUM(NSInteger, BCPlayerRenderMode, open) {
  BCPlayerRenderModeFILL_SCREEN = 0,
  BCPlayerRenderModeFILL_EDGE = 1,
};

typedef SWIFT_ENUM(NSInteger, BCPlayerStatus, open) {
  BCPlayerStatusPlay = 0,
  BCPlayerStatusPause = 1,
};

@class BCRewardAdContext;
SWIFT_PROTOCOL("_TtP10BCDramaLib17BCRewardAdAdapter_")
@protocol BCRewardAdAdapter <NSObject>
- (void)presentRewardFrom:(UIViewController * _Nonnull)viewController context:(BCRewardAdContext * _Nonnull)context;
@end

SWIFT_CLASS("_TtC10BCDramaLib21BCRewardAdCloseResult")
@interface BCRewardAdCloseResult : NSObject
@property (nonatomic) BOOL isEffective;
@property (nonatomic) double ecpm;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC10BCDramaLib17BCRewardAdContext")
@interface BCRewardAdContext : NSObject
@property (nonatomic, copy) NSString * _Nonnull placementId;
@property (nonatomic, copy) NSString * _Nonnull taskId;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull extraInfo;
@property (nonatomic, weak) UIViewController * _Nullable rewardPresenter;
@property (nonatomic, copy) void (^ _Nullable onEffective)(void);
@property (nonatomic, copy) void (^ _Nullable onClosed)(BCRewardAdCloseResult * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onFailed)(NSError * _Nullable);
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// 标记 SDK 根界面是否在前台展示，供宿主在 <code>application(_:supportedInterfaceOrientationsFor:)</code> 中在展示 SDK 时返回 <code>.portrait</code>，
/// 与 Info.plist 取交集后可避免「先横屏再被拉回竖屏」的闪烁。
SWIFT_CLASS_NAMED("BCSdkOrientationSession")
@interface BCSdkOrientationSession : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isActive;)
+ (BOOL)isActive SWIFT_WARN_UNUSED_RESULT;
+ (void)push;
+ (void)pop;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC10BCDramaLib19BCSegmentedBaseCell")
@interface BCSegmentedBaseCell : UICollectionViewCell
- (void)prepareForReuse;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, getter=isSelected) BOOL selected;
@property (nonatomic, getter=isHighlighted) BOOL highlighted;
@end

SWIFT_CLASS("_TtC10BCDramaLib25BCSegmentedCollectionView")
@interface BCSegmentedCollectionView : UICollectionView
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame collectionViewLayout:(UICollectionViewLayout * _Nonnull)layout OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC10BCDramaLib31BCSegmentedComponetGradientView")
@interface BCSegmentedComponetGradientView : UIView
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) Class _Nonnull layerClass;)
+ (Class _Nonnull)layerClass SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC10BCDramaLib20BCSegmentedTitleCell")
@interface BCSegmentedTitleCell : BCSegmentedBaseCell
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC10BCDramaLib18BCSegmentedDotCell")
@interface BCSegmentedDotCell : BCSegmentedTitleCell
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC10BCDramaLib28BCSegmentedIndicatorBaseView")
@interface BCSegmentedIndicatorBaseView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

/// 不支持indicatorPosition、verticalOffset。默认垂直居中。
SWIFT_CLASS("_TtC10BCDramaLib34BCSegmentedIndicatorBackgroundView")
@interface BCSegmentedIndicatorBackgroundView : BCSegmentedIndicatorBaseView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC10BCDramaLib31BCSegmentedIndicatorDotLineView")
@interface BCSegmentedIndicatorDotLineView : BCSegmentedIndicatorBaseView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC10BCDramaLib34BCSegmentedIndicatorDoubleLineView")
@interface BCSegmentedIndicatorDoubleLineView : BCSegmentedIndicatorBaseView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC10BCDramaLib28BCSegmentedIndicatorLineView")
@interface BCSegmentedIndicatorLineView : BCSegmentedIndicatorBaseView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

/// 会无视indicatorColor属性，以gradientColors为准
SWIFT_CLASS("_TtC10BCDramaLib36BCSegmentedIndicatorGradientLineView")
@interface BCSegmentedIndicatorGradientLineView : BCSegmentedIndicatorLineView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

/// 整个背景是一个渐变色layer，通过gradientMaskLayer遮罩显示不同位置，达到不同文字底部有不同的渐变色。
SWIFT_CLASS("_TtC10BCDramaLib32BCSegmentedIndicatorGradientView")
@interface BCSegmentedIndicatorGradientView : BCSegmentedIndicatorBaseView
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) Class _Nonnull layerClass;)
+ (Class _Nonnull)layerClass SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC10BCDramaLib29BCSegmentedIndicatorImageView")
@interface BCSegmentedIndicatorImageView : BCSegmentedIndicatorBaseView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

/// 会无视indicatorColor属性，以indicatorColors为准
SWIFT_CLASS("_TtC10BCDramaLib35BCSegmentedIndicatorRainbowLineView")
@interface BCSegmentedIndicatorRainbowLineView : BCSegmentedIndicatorLineView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC10BCDramaLib32BCSegmentedIndicatorTriangleView")
@interface BCSegmentedIndicatorTriangleView : BCSegmentedIndicatorBaseView
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) Class _Nonnull layerClass;)
+ (Class _Nonnull)layerClass SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC10BCDramaLib28BCSegmentedListContainerView")
@interface BCSegmentedListContainerView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)willMoveToSuperview:(UIView * _Nullable)newSuperview;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@interface BCSegmentedListContainerView (SWIFT_EXTENSION(BCDramaLib)) <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
@end

@protocol BCSegmentedListContainerViewListDelegate;
SWIFT_PROTOCOL("_TtP10BCDramaLib38BCSegmentedListContainerViewDataSource_")
@protocol BCSegmentedListContainerViewDataSource
/// 返回list的数量
- (NSInteger)numberOfListsIn:(BCSegmentedListContainerView * _Nonnull)listContainerView SWIFT_WARN_UNUSED_RESULT;
/// 根据index初始化一个对应列表实例，需要是遵从<code>BCSegmentedListContainerViewListDelegate</code>协议的对象。
/// 如果列表是用自定义UIView封装的，就让自定义UIView遵从<code>BCSegmentedListContainerViewListDelegate</code>协议，该方法返回自定义UIView即可。
/// 如果列表是用自定义UIViewController封装的，就让自定义UIViewController遵从<code>BCSegmentedListContainerViewListDelegate</code>协议，该方法返回自定义UIViewController即可。
/// 注意：一定要是新生成的实例！！！
/// \param listContainerView BCSegmentedListContainerView
///
/// \param index 目标index
///
///
/// returns:
/// 遵从BCSegmentedListContainerViewListDelegate协议的实例
- (id <BCSegmentedListContainerViewListDelegate> _Nonnull)listContainerView:(BCSegmentedListContainerView * _Nonnull)listContainerView initListAt:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
@optional
/// 控制能否初始化对应index的列表。有些业务需求，需要在某些情况才允许初始化某些列表，通过通过该代理实现控制。
- (BOOL)listContainerView:(BCSegmentedListContainerView * _Nonnull)listContainerView canInitListAt:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
/// 返回自定义UIScrollView或UICollectionView的Class
/// 某些特殊情况需要自己处理UIScrollView内部逻辑。比如项目用了FDFullscreenPopGesture，需要处理手势相关代理。
/// \param listContainerView BCSegmentedListContainerView
///
///
/// returns:
/// 自定义UIScrollView实例
- (Class _Nonnull)scrollViewClassIn:(BCSegmentedListContainerView * _Nonnull)listContainerView SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_PROTOCOL("_TtP10BCDramaLib40BCSegmentedListContainerViewListDelegate_")
@protocol BCSegmentedListContainerViewListDelegate
/// 如果列表是VC，就返回VC.view
/// 如果列表是View，就返回View自己
///
/// returns:
/// 返回列表视图
- (UIView * _Nonnull)listView SWIFT_WARN_UNUSED_RESULT;
@optional
- (void)listWillAppear;
- (void)listDidAppear;
- (void)listWillDisappear;
- (void)listDidDisappear;
@end

SWIFT_CLASS("_TtC10BCDramaLib21BCSegmentedNumberCell")
@interface BCSegmentedNumberCell : BCSegmentedTitleCell
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC10BCDramaLib29BCSegmentedTitleAttributeCell")
@interface BCSegmentedTitleAttributeCell : BCSegmentedBaseCell
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC10BCDramaLib28BCSegmentedTitleGradientCell")
@interface BCSegmentedTitleGradientCell : BCSegmentedTitleCell
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC10BCDramaLib25BCSegmentedTitleImageCell")
@interface BCSegmentedTitleImageCell : BCSegmentedTitleCell
- (void)prepareForReuse;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC10BCDramaLib27BCSegmentedTitleOrImageCell")
@interface BCSegmentedTitleOrImageCell : BCSegmentedTitleCell
- (void)prepareForReuse;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

/// 内部会自己找到父UIViewController，然后将其automaticallyAdjustsScrollViewInsets设置为false，这一点请知晓。
SWIFT_CLASS("_TtC10BCDramaLib15BCSegmentedView")
@interface BCSegmentedView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)willMoveToSuperview:(UIView * _Nullable)newSuperview;
- (void)layoutSubviews;
- (void)observeValueForKeyPath:(NSString * _Nullable)keyPath ofObject:(id _Nullable)object change:(NSDictionary<NSKeyValueChangeKey, id> * _Nullable)change context:(void * _Nullable)context;
@end

@interface BCSegmentedView (SWIFT_EXTENSION(BCDramaLib)) <UICollectionViewDelegate>
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end

@interface BCSegmentedView (SWIFT_EXTENSION(BCDramaLib)) <UICollectionViewDataSource>
- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView * _Nonnull)collectionView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end

@interface BCSegmentedView (SWIFT_EXTENSION(BCDramaLib)) <UICollectionViewDelegateFlowLayout>
- (UIEdgeInsets)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout insetForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumLineSpacingForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumInteritemSpacingForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
@end

/// 广告显示策略 1、竞价策略（不支持穿山甲） 2、轮循策略  (目前仅支持轮询)
typedef SWIFT_ENUM(NSInteger, BCStrategyType, open) {
  BCStrategyTypeBidding = 1,
  BCStrategyTypeRound = 2,
};

@class UITab;
SWIFT_CLASS("_TtC10BCDramaLib18BCTabBarController")
@interface BCTabBarController : UITabBarController
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
@property (nonatomic, readonly) BOOL shouldAutorotate;
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
@property (nonatomic, readonly) UIInterfaceOrientation preferredInterfaceOrientationForPresentation;
- (nonnull instancetype)initWithTabs:(NSArray<UITab *> * _Nonnull)tabs OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=18.0);
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

/// 内容page页
typedef SWIFT_ENUM(NSInteger, BCTabPageType, open) {
  BCTabPageTypeCollection = 0,
  BCTabPageTypeAlbum = 1,
  BCTabPageTypeRecommend = 2,
};

typedef SWIFT_ENUM(NSInteger, BCUnLockType, open) {
  BCUnLockTypePayment = 0,
  BCUnLockTypeReward = 1,
};

SWIFT_CLASS_NAMED("BCUnlockVideoListModel")
@interface BCUnlockVideoListModel : NSObject
@property (nonatomic) NSInteger episode_no;
@property (nonatomic, copy) NSString * _Nonnull last_play_time;
@property (nonatomic, copy) NSString * _Nonnull logo_img;
@property (nonatomic) NSInteger video_id;
@property (nonatomic, copy) NSString * _Nonnull video_title;
@property (nonatomic) NSInteger video_total;
@property (nonatomic) NSInteger max_unlock_episode_no;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("BCUnlockVideoModel")
@interface BCUnlockVideoModel : NSObject
@property (nonatomic) NSInteger page;
@property (nonatomic) NSInteger page_size;
@property (nonatomic) NSInteger total;
@property (nonatomic) NSInteger pages;
@property (nonatomic, copy) NSArray<BCUnlockVideoListModel *> * _Nonnull list;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("BCUserInfosModel")
@interface BCUserInfosModel : NSObject
@property (nonatomic, copy) NSString * _Nonnull user_id;
@property (nonatomic) NSInteger expire_time;
@property (nonatomic, copy) NSString * _Nonnull user_no;
@property (nonatomic, copy) NSString * _Nonnull nickname;
@property (nonatomic, copy) NSString * _Nonnull avatar;
@property (nonatomic) NSInteger video_attribute_sex;
@property (nonatomic) NSInteger is_vip;
@property (nonatomic, copy) NSString * _Nonnull vip_expire_date;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// 常用工具专用类，后续公共方法都放在这个类，或者它的扩展类
SWIFT_CLASS("_TtC10BCDramaLib14BCUtilsManager")
@interface BCUtilsManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC10BCDramaLib14BCVideoManager")
@interface BCVideoManager : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@interface BCVideoManager (SWIFT_EXTENSION(BCDramaLib))
/// 初始化SDK
/// \param appId BCVideoSDK的AppId
///
/// \param packageName 包名（bundleId）
///
/// \param secret 签名秘钥
///
/// \param userId app端用户唯一标识
///
+ (void)initSDKWithAppId:(NSString * _Nonnull)appId packageName:(NSString * _Nonnull)packageName secret:(NSString * _Nonnull)secret userId:(NSString * _Nonnull)userId adAdapters:(NSArray<id <BCAdAdapter>> * _Nonnull)adAdapters isInitSuccess:(void (^ _Nonnull)(BOOL))isInitSuccess SWIFT_METHOD_FAMILY(none);
/// 退出登录
+ (void)logout;
/// 进入首页
/// \param vc 来源控制器
///
/// \param pageType page 类型
///
+ (void)showSDKFrom:(UIViewController * _Nonnull)vc pageType:(enum BCTabPageType)pageType;
/// 进入在追
/// \param vc 来源控制器
///
+ (void)showCollectionPageFrom:(UIViewController * _Nonnull)vc;
/// 进入剧单
/// \param vc 来源控制器
///
+ (void)showAlbumListPageFrom:(UIViewController * _Nonnull)vc;
/// 进入推荐
/// \param vc 来源控制器
///
+ (void)showRecommendPageFrom:(UIViewController * _Nonnull)vc;
/// 获取首页控制器
/// \param pageType page 类型
///
+ (UIViewController * _Nonnull)getHomePageWithPageType:(enum BCTabPageType)pageType topOffset:(CGFloat)topOffset SWIFT_WARN_UNUSED_RESULT;
/// 获取在追页控制器
/// \param vc 来源控制器
///
+ (UIViewController * _Nonnull)getCollectionPageWithTopOffset:(CGFloat)topOffset topTabBarOffsetY:(CGFloat)topTabBarOffsetY SWIFT_WARN_UNUSED_RESULT;
/// 跳转到在追页控制器, 并设置播放页顶部工具栏Y轴偏移量
/// \param vc 来源控制器
///
/// \param topOffset 在追页偏移量
///
/// \param topTabBarOffsetY 设置播放页顶部工具栏的偏移量（优先级高于BCLoginManager.shared.playerTopBarOffsetY）
///
+ (void)toCollectionViewControllerFrom:(UIViewController * _Nonnull)vc topOffset:(CGFloat)topOffset topTabBarOffsetY:(CGFloat)topTabBarOffsetY;
/// 获取剧单页控制器
/// <ul>
///   <li>
///     topOffset: 剧单页偏移量
///   </li>
///   <li>
///     hOffset: 横向偏移量
///   </li>
///   <li>
///     topTabBarOffsetY: 设置播放页顶部工具栏的偏移量（优先级高于BCLoginManager.shared.playerTopBarOffsetY）
///   </li>
/// </ul>
+ (UIViewController * _Nonnull)getAlbumListPageWithTopOffset:(CGFloat)topOffset hOffset:(CGFloat)hOffset topTabBarOffsetY:(CGFloat)topTabBarOffsetY SWIFT_WARN_UNUSED_RESULT;
/// 跳转到剧单页控制器, 并设置播放页顶部工具栏Y轴偏移量
/// \param topOffset 剧单页偏移量
///
/// \param topTabBarOffsetY 设置播放页顶部工具栏的偏移量（优先级高于BCLoginManager.shared.playerTopBarOffsetY）
///
/// \param vc 来源控制器
///
+ (void)toAlbumListViewControllerFrom:(UIViewController * _Nonnull)vc topOffset:(CGFloat)topOffset hOffset:(CGFloat)hOffset topTabBarOffsetY:(CGFloat)topTabBarOffsetY;
/// 获取推荐页控制器
/// \param vc 来源控制器
///
/// \param topTabBarOffsetY 设置播放页顶部工具栏的偏移量（优先级高于BCLoginManager.shared.playerTopBarOffsetY）
///
+ (UIViewController * _Nonnull)getRecommendPageWithTopOffset:(CGFloat)topOffset topTabBarOffsetY:(CGFloat)topTabBarOffsetY SWIFT_WARN_UNUSED_RESULT;
/// 跳转到推荐页, 并设置播放页顶部工具栏Y轴偏移量
/// \param vc 来源控制器
///
/// \param topOffset 顶部偏移量
///
/// \param topTabBarOffsetY 设置播放页顶部工具栏的偏移量（优先级高于BCLoginManager.shared.playerTopBarOffsetY）
///
+ (void)toRecommendVcFrom:(UIViewController * _Nonnull)vc topOffset:(CGFloat)topOffset topTabBarOffsetY:(CGFloat)topTabBarOffsetY;
/// 设置国际化多语言
/// \param type 语言地区类型
///
+ (void)setLanguageWithType:(enum BCLanguageType)type;
/// 设置视频播放回调
/// \param onStart 开始的回调
///
/// \param onProgress 进度的回调: 参数1：剧集索引，参数2: pageType，参数3：获取当前播放时间 参数4：获取视频总时长 参数5：可播放时长
///
/// \param onEnd 结束的回调
///
/// \param onUnlock 解锁的回调
///
/// \param onReward 奖励的回调
///
+ (void)setVideoPlayCallBackOnStart:(void (^ _Nullable)(NSDictionary<NSString *, id> * _Nonnull))onStart onProgress:(void (^ _Nullable)(NSString * _Nonnull, NSInteger, NSInteger, NSInteger, NSInteger))onProgress onEnd:(void (^ _Nullable)(NSDictionary<NSString *, id> * _Nonnull))onEnd onUnlock:(void (^ _Nullable)(NSDictionary<NSString *, id> * _Nonnull))onUnlock onReward:(void (^ _Nullable)(NSDictionary<NSString *, id> * _Nonnull))onReward;
/// 设置开发环境
/// 若是手动调用，需要在初始化方法前调用
/// \param type 环境类型：0：生产环境， 1：开发环境
///
+ (void)setEnvWithType:(enum BCEnvType)type;
/// 当短剧SDK里面选择商品点击商品时，调用对应的回调
/// \param onPayment 商品参数JSON
///
+ (void)setPaymentCallbackOnPayment:(void (^ _Nullable)(NSDictionary<NSString *, id> * _Nonnull))onPayment;
/// 支付设置的回调
/// \param onPaySuccess 支付成功后的回调
///
+ (void)setPaymentOnPaySuccess:(void (^ _Nullable)(NSDictionary<NSString *, id> * _Nonnull))onPaySuccess;
/// 当付款成功后调用此方法通知短剧sdk验证订单付款状态
/// \param onPaySuccess 支付成功后的回调
///
+ (void)paymentResultVerifyOnPayVerify:(void (^ _Nullable)(NSInteger))onPayVerify;
/// 查询订单支付状态
/// \param orderNo 订单号
///
///
/// returns:
/// 支付状态
+ (void)verifyPaymentResultWithOrderNo:(NSString * _Nonnull)orderNo retryCount:(NSInteger)retryCount complet:(void (^ _Nonnull)(NSInteger))complet;
/// 取消付款，当用户取消支付时调用此方法。
/// \param onPayCancle 取消支付的回调
///
+ (void)paymentCancelOnPayCancle:(void (^ _Nullable)(void))onPayCancle;
/// 设置广告加载的回调
/// \param onLoaded 加载成功后的回调
///
/// \param onClicked 广告被点击的回调
///
/// \param onEffective 广告发放奖励后的回调（仅有激励视频有奖励的回调）
///
/// \param onClosed 广告关闭后的回调
///
/// \param onFiled 广告加载失败后的回调
///
+ (void)loadVideoAdCallbackOnLoaded:(void (^ _Nullable)(enum BCAdType, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))onLoaded onClicked:(void (^ _Nullable)(enum BCAdType))onClicked onEffective:(void (^ _Nullable)(enum BCAdType, NSInteger))onEffective onClosed:(void (^ _Nullable)(enum BCAdType))onClosed onFailed:(void (^ _Nullable)(enum BCAdType, NSError * _Nonnull))onFailed;
/// 设置广告加载的回调
/// \param onLoaded 加载成功后的回调
///
+ (void)loadAdvSuccessOnLoaded:(void (^ _Nullable)(enum BCAdType, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))onLoaded;
/// 设置广告加载的回调
/// \param onClicked 广告被点击的回调
///
+ (void)loadAdvOnClickedOnClicked:(void (^ _Nullable)(enum BCAdType))onClicked;
/// 设置广告加载的回调
/// \param onEffective 广告发放奖励后的回调（仅有激励视频有奖励的回调）
///
+ (void)loadAdvEffectiveOnEffective:(void (^ _Nullable)(enum BCAdType, NSInteger))onEffective;
/// 设置广告加载的回调
/// \param onClosed 广告关闭后的回调
///
+ (void)loadAdvOnClosedOnClosed:(void (^ _Nullable)(enum BCAdType))onClosed;
/// 设置广告加载的回调
/// \param onFailed 广告加载失败后的回调
///
+ (void)loadAdvOnFailedOnFailed:(void (^ _Nullable)(enum BCAdType, NSError * _Nonnull))onFailed;
/// 设置广告加载的回调
/// \param onFinished 广告加载完成的回调
///
+ (void)loadAdvOnShowFinishedOnFinished:(void (^ _Nullable)(NSInteger))onFinished;
/// 设置广告加载的回调
/// \param onRender 信息流广告渲染是否成功的回调
///
+ (void)loadNativeExpressRenderOnRender:(void (^ _Nullable)(enum BCAdType, BOOL))onRender;
/// 自定义广告回调
/// \param initAd 初始化广告
///
/// \param rewardAd 自定义激励广告
///
/// \param nativeExpressAd 自定义信息流广告
///
/// \param bannerAd 自定义banner广告
///
+ (void)setCustomAdvCallbackWithInitAd:(void (^ _Nullable)(NSString * _Nonnull))initAd rewardAd:(void (^ _Nullable)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))rewardAd nativeExpressAd:(void (^ _Nullable)(NSString * _Nonnull, double, double))nativeExpressAd bannerAd:(void (^ _Nullable)(NSString * _Nonnull))bannerAd;
/// 设置默认播放速度，正常播放传1X，默认为1.25X
/// 支持 0.75X、1.0X、1.25X、1.5X、2.0X
/// \param videoId 剧ID
///
/// \param rate 播放速率
///
+ (void)setVideoDefaultRateWithVideoId:(NSInteger)videoId rate:(double)rate;
/// 剧集解锁是否成功的回调
/// \param onUnLock 验证剧集是否解锁后的回调
///
+ (void)onUnLockOnUnLock:(void (^ _Nullable)(enum BCUnLockType, NSInteger))onUnLock;
/// 广告播放完成，奖励发放回调
/// \param onFinish 广告播放完成后发放奖励的回调
///
+ (void)onAdDidFinishOnFinish:(void (^ _Nullable)(NSInteger))onFinish;
/// 开始激励视频
/// \param vc 来源控制器
///
/// \param videoId 短剧Id
///
/// \param eposodeNo 剧集索引
///
/// \param placementId 广告位ID
///
/// \param extra 扩展信息
///
/// \param onStartReward 开始激励视频的回调
///
/// \param onAdFiled 激励视频加载失败的回调
///
+ (void)startRewardVideoWithForm:(UIViewController * _Nonnull)vc videoId:(NSInteger)videoId eposodeNo:(NSInteger)eposodeNo placementId:(NSString * _Nonnull)placementId extra:(NSDictionary<NSString *, id> * _Nonnull)extra onStartReward:(void (^ _Nullable)(enum BCAdPlatformType, enum BCAdType))onStartReward;
/// 进入播放页
/// \param vc 来源控制器
///
/// \param videoId 剧ID
///
/// \param lastEpisodeNo 播放的剧集索引
///
/// \param offsetY 播放页顶部工具栏的Y轴偏移量
///
+ (void)jumpToVideoPlayControllerFrom:(UIViewController * _Nonnull)vc videoId:(NSInteger)videoId lastEpisodeNo:(NSInteger)lastEpisodeNo offsetY:(CGFloat)offsetY;
/// 进入剧单更多-剧列表
/// \param vc 来源控制器
///
/// \param menuId 剧单ID
///
+ (void)jumpToVideoMoreDetailListFrom:(UIViewController * _Nonnull)vc menuId:(NSInteger)menuId menuName:(NSString * _Nonnull)menuName;
/// 收藏记录-(需要先初始化，确保已登录SDK)
/// \param page 页数索引
///
/// \param pageSize 每页多少条收藏记录
/// 备注：返回值1：数据模型类，返回值2：error
///
+ (void)getCollectionRecordsWithPage:(NSInteger)page pageSize:(NSInteger)pageSize comolete:(void (^ _Nonnull)(NSArray<BCDramaFavoriteListModel *> * _Nullable, NSString * _Nullable))comolete;
/// 获取播放剧集列表接口
/// \param page 页数索引
///
/// \param pageSize 每页多少条收藏记录
/// 备注：返回值1：数据模型类，返回值2：error
///
+ (void)getHistoryListWithPage:(NSInteger)page pageSize:(NSInteger)pageSize comolete:(void (^ _Nonnull)(NSArray<BCDramaFavoriteListModel *> * _Nullable, NSString * _Nullable))comolete;
/// 是否隐藏播放页的点赞功能
/// \param isHidden 是否隐藏（默认：不隐藏）
///
+ (void)hideTheLikeActionWithIsHidden:(BOOL)isHidden;
/// 是否隐藏播放页收藏功能
/// \param isHidden 是否隐藏（默认：不隐藏）
///
+ (void)hideTheCollectionActionWithIsHidden:(BOOL)isHidden;
/// 设置播放器顶部工具栏的Y轴偏移量， 备注：优先级低于直接进入控制器传入的topBarOffsetY
/// 初始化的时候配置，退出登录的时候会被重置为默认
/// \param offsetY Y轴偏移量
///
+ (void)setPlayerTopTabBarOffsetYWithOffsetY:(CGFloat)offsetY;
/// 关闭SDK支付功能 1： 开启  0：关闭
/// 初始化的时候配置，退出登录的时候会被重置为默认
/// \param payment 是否需要关闭SDK支付功能(默认： 开启)
///
+ (void)setPayActionStatusWithPayment:(enum BCPaymentStatus)payment;
/// 获取SDK版本号（SDK没有特殊要求版本号，这里做便于版本管理的对外函数）
///
/// returns:
/// 版本号
+ (NSString * _Nonnull)getSDKVersion SWIFT_WARN_UNUSED_RESULT;
/// 进入新版SDK的根控制器（默认选中首页）
/// \param vc 导航栈
///
/// \param selectedIndex 默认显示第几个导航器（默认仅支持0：首页， 1： 为你推荐页， 2： 我的剧单页）
///
+ (BCTabBarController * _Nonnull)goToRootViewControllerWithForm:(UIViewController * _Nonnull)vc selectedIndex:(NSInteger)selectedIndex SWIFT_WARN_UNUSED_RESULT;
/// 获取新版推荐页
/// \param vc 外层控制的导航栈
///
/// \param toolOffsetY 播放页顶部工具条的Y轴偏移量
///
///
/// returns:
/// 推荐页(备注：与老版本的推荐页是分开的，目的是防止后续推荐页更改样式，同时SDK保留和兼容老版本推荐页)
+ (UIViewController * _Nonnull)getRecommendViewControllerWithForm:(UIViewController * _Nonnull)vc toolOffsetY:(CGFloat)toolOffsetY SWIFT_WARN_UNUSED_RESULT;
/// 获取新版我的剧集页
/// \param vc 导航栈控制器源
///
/// \param isHiddenNav 是否隐藏SDK自带导航条
///
/// \param toolOffsetY 播放页顶部工具条的Y轴偏移量
///
/// \param contentInsert 内边距
///
///
/// returns:
/// 我的剧集页 推荐页(备注：与老版本的剧集页是分开的，目的是防止后续剧集页更改样式，同时SDK保留和兼容老版本剧集页)
+ (UIViewController * _Nonnull)getDramasViewControllerWithForm:(UIViewController * _Nonnull)vc isHiddenNav:(BOOL)isHiddenNav toolOffsetY:(CGFloat)toolOffsetY isHddenEmptyAction:(BOOL)isHddenEmptyAction contentInsert:(UIEdgeInsets)contentInsert SWIFT_WARN_UNUSED_RESULT;
/// 获取新版首页
/// \param vc 导航栈控制器源
///
///
/// returns:
/// 首页样式改版
+ (UIViewController * _Nonnull)getHomeViewControllerWithForm:(UIViewController * _Nonnull)vc SWIFT_WARN_UNUSED_RESULT;
/// 自定义播放页剧集封面图占位图 (默认： 不显示占位图)
/// \param imageName 播放器封面占位图URL（若imageName为空：则不显示默认占位图,  若imageName不为空，则显示自定义占位图）
/// 备注：需要将自定义占位图片添加到BCDramaLib的images目录下
///
+ (void)setPlayerCustomCoverPlaceholderImageWithImageName:(NSString * _Nullable)imageName;
/// 进入搜索页
/// \param vc 导航栈
///
+ (void)toSearchViewControllerWithForm:(UIViewController * _Nonnull)vc;
/// 点击商品列表的支付回调；备注：若使用自定义的支付方式实现，支付完成后必须调用onPayComplete函数进行订单的查询校验，否则无法解锁剧集
/// \param isCustomPayment 是否使用自定义支付方式（默认：SDK的支付宝、微信等现金支付）, 备注：自定义支付方式一定要设置为true
///
/// \param onPay 点击商品的回调
///
+ (void)onPaymentListenerWithIsCustomPayment:(BOOL)isCustomPayment onPay:(void (^ _Nullable)(NSString * _Nonnull, BCGoodItemsModel * _Nonnull, UIViewController * _Nonnull))onPay;
/// 自定义支付方式支付完成后的订单校验；备注：自定义支付方式支付完成后必须调用该函数进行订单的校验，否则无法解锁剧集
/// \param orderNo 订单号
///
/// \param videoId 剧ID
///
/// \param episodeNo 剧集索引
///
+ (void)onPayCompleteWithOrderNo:(NSString * _Nonnull)orderNo videoId:(NSInteger)videoId episodeNo:(NSInteger)episodeNo;
/// 防止外层即使离开播放页，没有调用viewDidDisappear这个生命周期函数，导致短剧没有暂停的问题
+ (void)pause;
+ (void)play;
/// 自定义广告-横幅广告初始化监听
/// \param onCustomBannerAd 横幅广告监听的回调
///
+ (void)loadCustomBannerAdOnCustomBannerAd:(void (^ _Nullable)(UIViewController * _Nonnull, UIView * _Nonnull, NSString * _Nonnull, enum BCCustomAdPageType, void (^ _Nullable)(void), void (^ _Nullable)(NSInteger)))onCustomBannerAd;
/// 自定义广告-激励视频广告初始化监听
/// \param onCustomRewardAd 激励视频监听回调
///
+ (void)loadCustomRewardAdOnCustomRewardAd:(void (^ _Nullable)(UIViewController * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, void (^ _Nullable)(void), void (^ _Nullable)(NSInteger)))onCustomRewardAd;
/// 自定义广告-全屏视频广告初始化监听
/// \param onCustomFullScreen 全屏广告监听回调
///
+ (void)loadCustomFullScreenAdOnCustomFullScreen:(void (^ _Nullable)(UIViewController * _Nonnull, NSString * _Nonnull, enum BCCustomAdPageType, void (^ _Nullable)(void), void (^ _Nullable)(NSInteger)))onCustomFullScreen;
/// 自定义广告-插屏视频广告初始化监听
/// \param onCustomFullScreen 插屏广告监听回调
///
+ (void)initCustomNativeAdOnCustomNative:(void (^ _Nullable)(UIViewController * _Nonnull, NSString * _Nonnull, enum BCCustomAdPageType, void (^ _Nullable)(void), void (^ _Nullable)(NSInteger)))onCustomNative SWIFT_METHOD_FAMILY(none);
/// 加载插屏广告
/// \param placementId 广告位ID
///
/// \param adType 广告类型
///
/// \param status 加载状态
///
/// \param pageType 来源页
///
/// \param adView 广告
///
/// \param adContainerView 展示广告的容器
///
/// \param onLoadCustonNativeCallBack 监听回调
///
+ (void)loadCustomNativeAdWithPlacementId:(NSString * _Nonnull)placementId adType:(enum BCAdType)adType status:(enum BCAdStatues)status pageType:(enum BCCustomAdPageType)pageType adView:(UIView * _Nonnull)adView adContainerView:(UIView * _Nonnull)adContainerView onLoadCustonNativeCallBack:(void (^ _Nullable)(UIView * _Nonnull))onLoadCustonNativeCallBack;
/// 自定义广告的状态改变监听
/// \param adType 广告类型
///
/// \param status 广告状态
///
/// \param pageType 来源页
///
/// \param isEffective 是否获得奖励（激励视频专属）
///
/// \param placementId 代码位
///
/// \param adView 广告View（不需要的就不传，具体看示例）
///
/// \param adContainerView 展示广告的容器
///
+ (void)customAdStatusChangedWithPlacementId:(NSString * _Nonnull)placementId adType:(enum BCAdType)adType status:(enum BCAdStatues)status pageType:(enum BCCustomAdPageType)pageType isEffective:(BOOL)isEffective adView:(UIView * _Nonnull)adView adContainerView:(UIView * _Nonnull)adContainerView;
/// 监听短剧的收藏状态
/// \param videoFavorite 收藏状态（回调参数1：VideoId  回调参数2：收藏状态（ 1-收藏，0-取消收藏））
///
+ (void)getVideoFavoriteStatusWithVideoFavorite:(void (^ _Nullable)(NSInteger, NSInteger))videoFavorite;
/// 监听短剧的点赞状态
/// \param videoFavorite 收藏状态（回调参数1：VideoId  回调参数2：收藏状态（ 1-点赞，0-取消点赞））
///
+ (void)getVideoLikesStatusWithVideoLikes:(void (^ _Nullable)(NSInteger, NSInteger))videoLikes;
/// 获取用户信息
/// \param comolete 参数1：用户信息的回调 参数2：错误信息error
///
+ (void)getUserInfosWithComolete:(void (^ _Nonnull)(BCUserInfosModel * _Nullable, NSString * _Nullable))comolete;
/// 获取已解锁的剧集列表
/// \param comolete 参数1：已解锁的剧集列表 参数2：错误信息error
///
/// \param page 页码
///
/// \param pageSize 页数
///
+ (void)getUnlockVideoListWithPage:(NSInteger)page pageSize:(NSInteger)pageSize comolete:(void (^ _Nonnull)(BCUnlockVideoModel * _Nullable, NSString * _Nullable))comolete;
/// 暂停播放器继续缓冲和播放
+ (void)pausePlayerBufferingAndPlay;
/// 监听播放器的状态
/// \param onPlayerStatus 播放器的状态回调（仅有播放和暂停，若需要其他，请反馈给我）
///
+ (void)playStatusOnPlayerStatus:(void (^ _Nullable)(enum BCPlayerStatus))onPlayerStatus;
/// 设置短剧是否静音
/// \param isMute 是否静音
///
+ (void)setPlayerIsMuteWithIsMute:(BOOL)isMute;
/// 监听播放器是否加载成功的回调
/// \param onPlayerLoadStatus 回调状态 - 参数1：剧ID（VideoId），参数2：剧索引（episodeNo），参数3：剧是否加载成功（eventId=-1000（剧列表获取失败，一般都是剧下架导致播放失败），eventId=2004（播放事件: 已经开始播放），负数值（除了（-1000））（点播错误: 当eventId值小于0就是播放器点播失败的错误））
///
+ (void)playerLoadStatusListenerOnPlayerLoadStatus:(void (^ _Nullable)(NSInteger, NSInteger, NSInteger))onPlayerLoadStatus;
/// 是否显示分享操作
/// \param isHidden 是否显示分享操作（默认隐藏）
///
+ (void)hiddenTheShareActionWithIsHidden:(BOOL)isHidden;
/// 监听分享操作的回调
/// \param onShareVideoCallBack 分享操作回调
///
+ (void)shareActionListenerOnShareVideoCallBack:(void (^ _Nullable)(UIViewController * _Nonnull, NSDictionary<NSString *, id> * _Nonnull))onShareVideoCallBack;
/// 获取充值记录列表
/// \param page 页数
///
/// \param pageSize 页码
///
/// \param comolete 回调
///
+ (void)getOrderListsWithPage:(NSInteger)page pageSize:(NSInteger)pageSize comolete:(void (^ _Nonnull)(BCPayOrderModel * _Nullable, NSString * _Nullable))comolete;
/// 是否隐藏首页导航条上的返回按钮（默认：隐藏）
/// \param isHidden 是否隐藏（true: 隐藏， false: 不隐藏）
///
+ (void)hideHomeNavBackWithIsHidden:(BOOL)isHidden;
/// 强制恢复SDK内部TabBar显示
/// \param animated 是否动画
///
+ (void)forceRestoreInternalTabBarWithAnimated:(BOOL)animated;
+ (void)setExternalTabBarControllerWithTabBarVc:(UITabBarController * _Nonnull)tabBarVc;
/// 启用/禁用完全隔离模式(默认是隔离的)
/// \param enabled 是否启用完全隔离模式
///
+ (void)setCompleteIsolationMode:(BOOL)enabled;
/// 显示SDK内部TabBar
/// \param animated 是否动画
///
+ (void)showInternalTabBarWithAnimated:(BOOL)animated;
/// 隐藏SDK内部TabBar
/// \param animated 是否动画
///
+ (void)hideInternalTabBarWithAnimated:(BOOL)animated;
/// 是否自定义商品列表面板
/// \param type 商品列表面板类型（默认：defaults, SDK自带面板，且数据是sdk自己获取, 最原始的样式）; half: 半自定义，商品列表面板使用SDK自带，但数据由外层给SDK；custom: 完全自定义，支付完成后需告知SDK进行校验,
///
/// \param onCustomGoodListViewCallBack 商品列表面板相关数据回调
///
+ (void)customGoodListViewWithType:(enum BCGoodListType)type onCustomGoodListViewCallBack:(void (^ _Nullable)(UIViewController * _Nonnull, NSArray<BCGoodListModel *> * _Nonnull, NSInteger, NSInteger))onCustomGoodListViewCallBack;
/// 获取支付商品订单的订单号（自定义支付，在付费前需要创建订单，后续会传给SDK，进行订单的校验）
/// \param goodsId 商品ID
///
/// \param videoId 剧ID
///
/// \param episodeNo 剧索引
///
/// \param payStrategyId 支付策略ID
///
+ (void)getGoodOrderNoWithGoodsId:(NSInteger)goodsId videoId:(NSInteger)videoId episodeNo:(NSInteger)episodeNo payStrategyId:(NSInteger)payStrategyId complete:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable))complete;
/// 半自定义模式显示商品列表自定义列表
/// \param goodList 商品列表模型列表数组
///
+ (void)showGoodListViewWithGoodList:(NSArray<BCGoodListModel *> * _Nonnull)goodList videoId:(NSInteger)videoId episodeNo:(NSInteger)episodeNo;
/// 完全自定义商品面板，但支付使用剧星收款方式进行解锁视频
/// \param goodModel 选中的商品模型
///
/// \param vc 展示支付面板的控制器源（就是customGoodListView监听函数中SDK传递给您的VC）
///
+ (void)payToUnlockVideoWithGoodModel:(BCGoodListModel * _Nonnull)goodModel vc:(UIViewController * _Nullable)vc;
/// 是否启动闪退监控（在初始化之前调用，默认是开启的）
+ (void)openCrashMonitoringWithIsOpenMonitoring:(BOOL)isOpenMonitoring;
/// 获取所有的闪退日志
+ (NSArray<NSString *> * _Nonnull)getAllCrashLogs SWIFT_WARN_UNUSED_RESULT;
/// 获取闪退日志数量
+ (NSInteger)getCrashLogCount SWIFT_WARN_UNUSED_RESULT;
/// 清除所有闪退日志
+ (void)clearAllCrashLogs;
/// 上传闪退日志到服务器
/// \param logs 日志内容
///
/// \param completion 完成后的回调(参数1： 上传成功的数量，参数2：上传失败后的回调)
///
+ (void)uploadLogToServerWithLogs:(NSArray<NSString *> * _Nonnull)logs completion:(void (^ _Nonnull)(NSInteger, NSInteger))completion;
/// 控制小窗口播放器视频是否静音
/// \param isMute 是否允许静音（默认: false）
///
+ (void)setPipPlayerMuteWithIsMute:(BOOL)isMute;
/// 手动移除小窗播放器的悬浮窗口
+ (void)removePipPlayerFloatView;
/// 监听开通会员的回调
/// \param onPay 支付的回调
///
+ (void)onRenewListenerOnPay:(void (^ _Nullable)(NSString * _Nonnull, BCGoodItemsModel * _Nonnull, UIViewController * _Nonnull))onPay;
/// 更新用户信息
+ (void)updateUserInformations;
/// 视频播放渲染模式
/// \param mode 展示模式
///
+ (void)setPlayerRenderModeWithMode:(enum BCPlayerRenderMode)mode;
+ (void)hideMeSettingBtn:(BOOL)isHidden;
+ (void)hideMeVipBtn:(BOOL)isHidden;
+ (void)setCustomUserAvater:(NSString * _Nullable)avater;
+ (void)setCustomUserNickname:(NSString * _Nullable)nickname;
@end

SWIFT_CLASS("_TtC10BCDramaLib19BCVideoPlayCallBack")
@interface BCVideoPlayCallBack : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) BCVideoPlayCallBack * _Nonnull shared;)
+ (BCVideoPlayCallBack * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) void (^ _Nullable onStart)(NSDictionary<NSString *, id> * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onProgress)(NSString * _Nonnull, NSInteger, NSInteger, NSInteger, NSInteger);
@property (nonatomic, copy) void (^ _Nullable onEnd)(NSDictionary<NSString *, id> * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onUnlock)(NSDictionary<NSString *, id> * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onReward)(NSDictionary<NSString *, id> * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onPayment)(NSDictionary<NSString *, id> * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onPaySuccess)(NSDictionary<NSString *, id> * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onPayCancle)(void);
@property (nonatomic, copy) void (^ _Nullable onAdLoaded)(enum BCAdType, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onAdClicked)(enum BCAdType);
@property (nonatomic, copy) void (^ _Nullable onAdEffective)(enum BCAdType, NSInteger);
@property (nonatomic, copy) void (^ _Nullable onAdClosed)(enum BCAdType);
@property (nonatomic, copy) void (^ _Nullable onAdFailed)(enum BCAdType, NSError * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onStartAdReward)(enum BCAdPlatformType, enum BCAdType);
@property (nonatomic, copy) void (^ _Nullable onAdUnLock)(enum BCUnLockType, NSInteger);
@property (nonatomic, copy) void (^ _Nullable onAdFinish)(NSInteger);
@property (nonatomic, copy) void (^ _Nullable initAdCallback)(NSString * _Nonnull);
- (void (^ _Nullable)(NSString * _Nonnull))initAdCallback SWIFT_METHOD_FAMILY(none) SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) void (^ _Nullable rewardAdCallback)(NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable nativeExpressAdCallback)(NSString * _Nonnull, double, double);
@property (nonatomic, copy) void (^ _Nullable bannerAdCallback)(NSString * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable payResultVerify)(NSInteger);
@property (nonatomic, copy) void (^ _Nullable onAdRenderStatus)(enum BCAdType, BOOL);
@property (nonatomic, copy) void (^ _Nullable onCustomPayment)(NSString * _Nonnull, BCGoodItemsModel * _Nonnull, UIViewController * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onCustomBannerAds)(UIViewController * _Nonnull, UIView * _Nonnull, NSString * _Nonnull, enum BCCustomAdPageType, void (^ _Nullable)(void), void (^ _Nullable)(NSInteger));
@property (nonatomic, copy) void (^ _Nullable onCustomRewardAds)(UIViewController * _Nonnull, NSString * _Nonnull, NSString * _Nonnull, void (^ _Nullable)(void), void (^ _Nullable)(NSInteger));
@property (nonatomic, copy) void (^ _Nullable onCustomFullScreenAds)(UIViewController * _Nonnull, NSString * _Nonnull, enum BCCustomAdPageType, void (^ _Nullable)(void), void (^ _Nullable)(NSInteger));
@property (nonatomic, copy) void (^ _Nullable onCustomNativeAds)(UIViewController * _Nonnull, NSString * _Nonnull, enum BCCustomAdPageType, void (^ _Nullable)(void), void (^ _Nullable)(NSInteger));
@property (nonatomic, copy) void (^ _Nullable onLoadCustonNativeCallBack)(UIView * _Nonnull);
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC10BCDramaLib11BCVodPlayer")
@interface BCVodPlayer : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class TXVodPlayer;
@interface BCVodPlayer (SWIFT_EXTENSION(BCDramaLib)) <TXVodPlayListener>
- (void)onPlayEvent:(TXVodPlayer * _Null_unspecified)player event:(int32_t)EvtID withParam:(NSDictionary * _Null_unspecified)param;
- (void)onNetStatus:(TXVodPlayer * _Null_unspecified)player withParam:(NSDictionary * _Null_unspecified)param;
@end

SWIFT_CLASS("_TtC10BCDramaLib18BCVodPlayerManager")
@interface BCVodPlayerManager : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC10BCDramaLib9ToastView")
@interface ToastView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
/// Toast 提示
/// \param message 提示内容
///
/// \param duration 显示时长， 默认 2.0 s
///
/// \param view 在哪个视图上显示，默认在window上显示
///
+ (void)showWithMessage:(NSString * _Nonnull)message duration:(NSTimeInterval)duration in:(UIView * _Nullable)view;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
